apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: tenant
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tenant
  minReplicas: 2
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
          averageUtilization: 60
          type: Utilization
  - type: Resource      
    resource:
       name: memory
       target:
          averageUtilization: 90
          type: Utilization
